#     ______                                           _____                  __
#    |   __ \.-----.-----.-----.--.--.----.----.-----.|     |_.-----.---.-.--|  |.-----.----.
#    |      <|  -__|__ --|  _  |  |  |   _|  __|  -__||       |  _  |  _  |  _  ||  -__|   _|
#    |___|__||_____|_____|_____|_____|__| |____|_____||_______|_____|___._|_____||_____|__|
#                                                             v.1.0

# Resource configuration.
resource:
  # Link to the resource pack.
  url: ""
  # A message when the player is prompted to install a resource pack.
  prompt: "&x&f&f&1&1&1&1Do you want to download this resource pack?"
  # Should players be prohibited from rejecting the download of a resource pack?
  force: true

# Messages configuration.
messages:
  # The message when the player rejected the download of the resource pack.
  resource-not-load: "&x&f&f&1&1&1&1You must download the resource pack to continue playing."
  # Settings reload command.
  reload:
    # A message when the plugin has successfully restarted.
    success: "&x&1&1&f&f&1&1Plugin success reloaded!"
    # A message when a player has specified the wrong argument.
    arg-not-found: "&x&f&f&1&1&1&1Arg &e{arg} &x&f&f&1&1&1&1not found."
    # Get help using the command.
    help: "&x&f&f&f&f&1&1Usage: /resource reload"
  # The message when the player don't have permissions to usage command.
  no-perms: "&x&f&f&1&1&1&1You don't have permissions."